---
- name: Otus kafka kraft install
  hosts: all
  become: true


  tasks:
    - name: provisioner info
      ansible.builtin.debug:
        msg: "Hi otus -task install kafka {{ node_id }}"


    - name: Include vars
      ansible.builtin.include_vars:
        file: main

    - name: configure server properties
      template:
        src: server.properties.j2
        dest: '{{installation_dir}}/config/kraft/server.properties'
        owner: "kafka"
        group: "kafka"
        mode: '0644'

    - name: Update the Java Heap Size for Kafka
      become: yes
      become_user: kafka
      replace:
        path: "{{installation_dir}}/bin/kafka-server-start.sh"
        regexp: 'export KAFKA_HEAP_OPTS=(".+")'
        replace: 'export KAFKA_HEAP_OPTS="-Xmx520M -Xms520M"'
        backup: yes

    - name: log directory setup
      become: yes
      become_user: kafka
      shell: |
        ./kafka-storage.sh format -t {{cluster_id}}  --ignore-formatted -c {{installation_dir}}/config/kraft/server.properties
      args:
        chdir: "{{installation_dir}}/bin"

    - name: Create a Service file for Kafka with Copy module
      become: yes
      copy:
        dest: /etc/systemd/system/kafka.service
        content: |
          [Unit]

          [Service]
          Type=simple
          User=kafka
          ExecStart=/bin/sh -c '{{installation_dir}}/bin/kafka-server-start.sh {{installation_dir}}/config/kraft/server.properties > {{installation_dir}}/kafkaservice.log 2>&1'
          ExecStop={{installation_dir}}/bin/kafka-server-stop.sh
          Restart=always
          RestartSec=30

          [Install]
          WantedBy=multi-user.target
        mode: 0755

    - name: Start Services
      become: yes
      systemd:
        name: '{{item}}'
        state: started
        enabled: yes
      with_items:
        - "kafka"
 
    - name: Validating if Kafka is up and listening on port 9092
      wait_for:
        host: localhost
        port: 9092
        delay: 10
        timeout: 30
        state: started
        msg: "Kafka not seem to be running"

    - name: Creating a directory for user conf
      ansible.builtin.file:
        path: "{{installation_dir}}/users_config"
        state: directory
        owner: "kafka"
        group: "kafka"
        mode: '647'

    - name: generate admin sasl properties
      template:
        src: admin.config.properties.j2
        dest: '{{installation_dir}}/users_config/admin.config.properties'
        owner: "kafka"
        group: "kafka"
        mode: '644'


    - name: generate client sasl properties
      template:
        src: sasl.config.properties.j2
        dest: '{{installation_dir}}/users_config/{{item}}.config.conf'
        owner: "kafka"
        group: "kafka"
        mode: '644'
      with_items:
        - "alice"
        - "bob"
        - "charlie"
      when: ansible_hostname == "kafka-server-3"

    - name: Create a Topic
      tags: createtopic
      shell: |
        ./kafka-topics.sh --create --topic {{topicname}}  --if-not-exists --bootstrap-server {{boot_srvs}} --command-config  {{installation_dir}}/users_config/admin.config.properties
      args:
        chdir: "{{installation_dir}}/bin"
      when: ansible_hostname == "kafka-server-3"

    - name: Set ACL Rules
      shell: |
        ./kafka-acls.sh --bootstrap-server {{boot_srvs}} --add --allow-principal User:alice --operation Write --topic {{topicname}}  --command-config  {{installation_dir}}/users_config/admin.config.properties
        ./kafka-acls.sh --bootstrap-server {{boot_srvs}} --add --allow-principal User:bob --operation Read --topic  {{topicname}}  --command-config  {{installation_dir}}/users_config/admin.config.properties
        ./kafka-acls.sh --bootstrap-server {{boot_srvs}} --add --allow-principal User:bob --operation Read - --group group.bob  --command-config  {{installation_dir}}/users_config/admin.config.properties
        ./kafka-acls.sh --bootstrap-server {{boot_srvs}} --list --command-config  {{installation_dir}}/users_config/admin.config.properties


      args:
        chdir: "{{installation_dir}}/bin"
      when: ansible_hostname == "kafka-server-3"