# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

 config.vm.define "otus_kafka" do |client|
    
    config.vm.box = "ubuntu/jammy64"   
    config.vm.synced_folder ".", "/vagrant", type: "rsync"

    client.vm.host_name = 'kafka-server'
    client.vm.network :private_network, ip: "192.168.56.101"
    client.vm.provider :virtualbox do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end  

    client.vm.provision "ansible_local" do |ansible|
      ansible.compatibility_mode = "2.0"
      ansible.playbook = "provisioners/kafka_install.yml"
      ansible.become = "true"
    end
 
  end

end
